-- import des données impossible avec table import data wizard et LOAD DATA LOCAL INFILE. Même problème sur tifosi et n’ayant pas encore eu la correction de mon devoir, j’importe donc une nouvelle fois les données à la main… 

-- messages de mysql workbench : 
-- 1. Unhandled exception: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128) Check the log for more details.
-- 2. Error Code: 3948. Loading local data is disabled; this must be enabled on both the client and server sides
-- 3. Error Code: 2068. LOAD DATA LOCAL INFILE file request rejected due to restrictions on access.
-- Pour régler le problème, j’ai modifié l’encodage du csv en passant en utf8 sans BOM. J’ai passé les virgules en point dans les notes. J’ai activé le loading data infile côté server et client. Sans résultat.  Si vous avez la solution, je suis preneur. 

INSERT INTO `trouveTonArtisan`.`Categorie` (`id_categorie`, `nom_categorie`) VALUES (NULL, 'Boucher');
INSERT INTO `trouveTonArtisan`.`Categorie` (`id_categorie`, `nom_categorie`) VALUES (NULL, 'Boulanger');
INSERT INTO `trouveTonArtisan`.`Categorie` (`id_categorie`, `nom_categorie`) VALUES (NULL, 'Chocolatier');
INSERT INTO `trouveTonArtisan`.`Categorie` (`id_categorie`, `nom_categorie`) VALUES (NULL, 'Traiteur');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Chauffagiste');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Electricien');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Menuisier');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Plombier');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Bijoutier');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Couturier');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Ferronier');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Coiffeur');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Fleuriste');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Toiletteur');
INSERT INTO `trouveTonArtisan`.`Categorie` (`nom_categorie`) VALUES ('Webdesign');

INSERT INTO `trouveTonArtisan`.`Specialite` (`nom_specialite`, `id_categorie`) VALUES ('Alimentation', '1');
INSERT INTO `trouveTonArtisan`.`Specialite` (`nom_specialite`, `id_categorie`) VALUES ('Batiment', '2');
INSERT INTO `trouveTonArtisan`.`Specialite` (`nom_specialite`, `id_categorie`) VALUES ('Fabrication', '3');
INSERT INTO `trouveTonArtisan`.`Specialite` (`nom_specialite`, `id_categorie`) VALUES ('Service', '4');


INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `top_artisan`) VALUES ('Boucherie Dumont', '1', '4.5', 'Lyon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'boucherie.dumond@gmail.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `top_artisan`) VALUES ('Au pain chaud', '2', '4.8', 'Montélimar', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'aupainchaud@hotmail.com', '1');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Chocolaterie Labbé', '3', '4.9', 'Lyon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'chocolaterie-labbe@gmail.com', 'https://chocolaterie-labbe.fr', '1');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Traiteur Truchon', '4', '4.1', 'Lyon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@truchon-traiteur.fr', 'https://truchon-traiteur.fr', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `top_artisan`) VALUES ('Orville Salmons', '5', '5', 'Evian', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'o-salmons@live.com', '1');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Mont Blanc Eléctricité', '6', '4.5', 'Chamonix', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@mont-blanc-electricite.com', 'https://mont-blanc-electricite.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Boutot & fils', '7', '4.7', 'Bourg-en-bresse', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'boutot-menuiserie@gmail.com', 'https://boutot-menuiserie.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Vallis Bellemare', '8', '4', 'Vienne', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'v.bellemare@gmail.com', 'https://plomberie-bellemare.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `top_artisan`) VALUES ('Claude Quinn', '9', '4.2', 'Aix-les-bains', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'claude.quinn@gmail.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Amitee Lécuyer', '10', '4.5', 'Annecy', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'a.amitee@hotmail.com', 'https://lecuyer-couture.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `top_artisan`) VALUES ('Ernest Carignan', '11', '5', 'Le Puy-en-Velay', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'e-carigan@hotmail.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `top_artisan`) VALUES ('Royden Charbonneau', '12', '3.8', 'Saint-Priest', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'r.charbonneau@gmail.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Leala Dennis', '12', '3.8', 'Chambéry', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'l.dennos@hotmail.fr', 'https://coiffure-leala-chambery.fr', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('C\'est sup\'hair', '12', '4.1', 'Romans-sur-Isère', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'sup-hair@gmail.com', 'https://sup-hair.fr', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('Le monde des fleurs', '13', '4.6', 'Annonay', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@le-monde-des-fleurs-annonay.fr', 'https://le-monde-des-fleurs-annonay.fr', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `top_artisan`) VALUES ('Valérie Laderoute', '14', '4.5', 'Valence', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'v-laredoute@gmail.com', '0');
INSERT INTO `trouveTonArtisan`.`Artisan` (`nom_artisan`, `id_specialite`, `note_artisan`, `ville_artisan`, `about_artisan`, `email_artisan`, `site_artisan`, `top_artisan`) VALUES ('CM Graphisme', '15', '4.4', 'Valence', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@cm-graphisme.com', 'https://cm-graphisme.com', '0');
